### ISSUE TITLE
Mobile responsiveness of Heading 

### ISSUE THREAD

**Issue by shivangi00** [shivangi00/ephemeral-strings#1]

**Comment by bitDrag** [comment]
I have already made necessary changes for making it responsive locally . Assign me to do this.

**Comment by shivangi00** [comment]
Hi @bitDrag ! Glad to see your willingness to contribute to the project. Although I was not planning for accepting external contributions, but seeing your efforts, I would review your pull request in some days (have my exams going on). 
I'm assigning this issue to you for the time being.

I would suggest you to make a separate branch and commit your changes and PRs from there rather than from  master to avoid conflicts.

Make sure to keep your master branch at par with the main project(updated repository). 
You can use the following command for that -
git pull upstream master

**Comment by bitDrag** [comment]
Okay I will make the changes. Thanks for the suggestions.
